Это грязь.
sberdevices/smart_app_framework pull request #14
Opened 2020-12-16 14:51 UTC by nlpfsd

2021-01-01 21:59 UTC, dangerink requested changes

2021-01-01 21:59 UTC, dangerink commented on smart_kit/start_points/main_loop_async_http.py
> +        app["database"] = app.loop.create_task(self.connect_to_db())
зачем коннектить к бд в бэкграунде, думаю что наоборот - нет смысла стартовать луп, пока нет коннекта - иначе получим странное поведение - параллельный процесс коннекта + хэндлинг сообщений(не факт что на момент обработки коннект появится)

2021-01-01 21:59 UTC, dangerink commented on smart_kit/start_points/main_loop_async_http.py
> +        aiohttp_config = self.settings["aiohttp"]
пул зеленых тредов задается в конфиге? кажестся нужно его как-то ограничить, учитывая что бОльшая часть операций cpu-bound

2021-01-11 13:38 UTC, nlpfsd commented on smart_kit/start_points/main_loop_async_http.py
> +        aiohttp_config = self.settings["aiohttp"]
зачем?

2021-01-12 12:36 UTC, dangerink commented on smart_kit/start_points/main_loop_async_http.py
> +        aiohttp_config = self.settings["aiohttp"]
иначе будет одновременно обрабатываться большое количество cpu-bound запросов и все будет равномерно тормозить, с пулом это решается подбором его размера

2021-01-13 08:08 UTC, nlpfsd commented on smart_kit/start_points/main_loop_async_http.py
> +        aiohttp_config = self.settings["aiohttp"]
и что? ты знаешь значения при которых приложение ломается?
зачем что-то ограничивать ради ограничения? Если кто-то хочет выстрелить себе в ногу, пусть стреляет, нет смысла вмешиваться.

2021-01-13 15:06 UTC, nlpfsd commented on smart_kit/start_points/main_loop_async_http.py
> +        app["database"] = app.loop.create_task(self.connect_to_db())
ну тут сыглы, правда не очень получилось

2021-01-14 14:13 UTC, ElephantsFoot requested changes

2021-01-14 14:13 UTC, ElephantsFoot commented on core/db_adapter/aioredis_adapter.py
> +import aioredis
не добавил зависимость в setup

2021-01-14 14:38 UTC, nlpfsd commented on core/db_adapter/aioredis_adapter.py
> +import aioredis
эт да

2021-01-14 14:57 UTC, dangerink submitted a review, later dismissed

2021-01-15 08:03 UTC, ElephantsFoot approved these changes

2021-01-15 10:32 UTC, dangerink approved these changes

2021-01-15 10:33 UTC, dangerink approved these changes

2021-01-15 11:41 UTC, merged