add set_local_variable action and implement local_vars logic
sberdevices/smart_app_framework pull request #15
Opened 2020-12-23 10:53 UTC by ElephantsFoot

2020-12-23 14:03 UTC, nlpfsd requested changes

2020-12-23 14:03 UTC, nlpfsd commented on scenarios/actions/action.py
> +class SetLocalVariableAction(Action):
а это, наследование там и все такое, забыл?

2020-12-23 14:40 UTC, ElephantsFoot commented on core/model/base_user.py
> +        self.local_vars = Variables(None, None)
потому что оно не должно сохраняться в БД через raw

2020-12-24 08:19 UTC, SokolovVladimir commented on scenarios/actions/action.py
> +        save_params[LOCAL_VARS] = copy.deepcopy(user.local_vars.values)
Можно использовать не copy.deepcopy, а более быструю версию from core.utils.pickle_copy import pickle_deepcopy

2021-01-01 21:38 UTC, dangerink submitted a review, later dismissed

2021-01-11 13:29 UTC, nlpfsd commented on core/model/base_user.py
> +        self.local_vars = Variables(None, None)
Тада надо сделать просто что raw возвращал None, там проверка на такое есть.

2021-01-11 13:58 UTC, nlpfsd approved these changes

2021-01-11 14:06 UTC, merged