DPNLPF-1060 added deep masking
sberdevices/smart_app_framework pull request #150
Opened 2021-11-11 11:14 UTC by sharifullinildus

2021-11-12 08:18 UTC, intsynko requested changes

2021-11-12 13:19 UTC, sharifullinildus commented on core/utils/masking_message.py
> +structure = {'token': ['***', '***', {'key': '*2*0*1*'}], 'notoken': [12, {'token': '***'}]}
перетащил примеры в тесты

2021-11-14 09:01 UTC, intsynko requested changes

2021-11-14 09:01 UTC, intsynko commented on core/utils/masking_message.py
> +                data[key] = '***'
Возможно тут стоит добавить тип поля, например так:
```python
data[key] = f'***{type(data[key])}'
```

2021-11-14 09:02 UTC, intsynko commented
Ну и надо сделать переносы строк длиннее 100 символов (в PyCharm есть ограничивающая строка) и пофиксить все места, где линтер ругается

2021-11-15 06:50 UTC, sharifullinildus commented
Все касаемо основной функции исправил, и пока что все же убрал функцию сложной маскировки, так как не думаю что в ней пока есть необходимость, врядли под ключами токен или профиль айди будут прям огромные структуры а по словарю самому все равно бегать функции поиска ключей для маскировки.

2021-11-18 14:06 UTC, intsynko commented on core/utils/masking_message.py
> +                data[key] = '***'
не хочешь, как хочешь)

2021-11-18 14:07 UTC, intsynko commented on core/utils/masking_message.py
> +from typing import Callable, Optional, Iterable, Mapping, Union, Pattern, Match, MutableMapping, List
List - не используется

2021-11-18 14:13 UTC, intsynko approved these changes

2021-11-22 14:09 UTC, intsynko approved these changes

2021-11-26 11:43 UTC, dangerink approved these changes

2021-11-26 11:43 UTC, merged