feature/add masking to logging from form fields
sberdevices/smart_app_framework pull request #158
Opened 2021-12-09 19:04 UTC by SyrexMinus

Added mask filled values in logs functionality.

Example:
(logs)
Before: QuestionField: Field: my_field filled by value: 123456789012345678
After: QuestionField: Field: my_field filled by value: ***

Usage:
In _static/configs/template_config.yml_ in _masking_fields_ add `name of the field` that is required to mask.

2021-12-16 15:11 UTC, intsynko requested changes

2021-12-16 15:11 UTC, intsynko commented on scenarios/scenario_models/field/field.py
> +        self._masking_fields = user.settings["template_settings"].get("masking_fields") if user is not None else []
Если поля `masking_fields` не будет в template_settings то будет None котрый в `masking` переназначится на `DEFAULT_MASKING_FIELDS` - это то поведение, которое мы хотим или может: `.get("masking_fields", [])`

2021-12-16 15:11 UTC, intsynko commented on scenarios/scenario_models/field/field.py
> +                  "field_value": str(dict_value[f"{self.description.name}"])}
а зачем сначала заворачивать в дикт, потом оттуда брать? masking вроде и с примитивом может работать

2021-12-16 21:42 UTC, SyrexMinus commented on scenarios/scenario_models/field/field.py
> +        self._masking_fields = user.settings["template_settings"].get("masking_fields") if user is not None else []
Пусть будет DEFAULT_MASKING_FIELDS, на случай, если разработчики забудут про маскирование секретных полей в template_settings. На то это и default-values :) . А если им будет правда необходимо ничего не маскировать, то они смогут это указать с помощью пустого поля в template_settings.

2021-12-16 21:57 UTC, SyrexMinus commented on scenarios/scenario_models/field/field.py
> +                  "field_value": str(dict_value[f"{self.description.name}"])}
Заворачивать нужно для того, чтобы можно было маскировать целое поле по его названию (в коде это `self.description.name`).

2021-12-17 07:31 UTC, intsynko commented on scenarios/scenario_models/field/field.py
> +        self._masking_fields = user.settings["template_settings"].get("masking_fields") if user is not None else []
А почему если юзер=None - то мы ничего не маскируем?

2021-12-17 07:47 UTC, SyrexMinus commented on scenarios/scenario_models/field/field.py
> +        self._masking_fields = user.settings["template_settings"].get("masking_fields") if user is not None else []
Такого, по идее, не должно быть (сценарий не может существовать без юзера). Такое может произойти при тестах, когда юзер мокается. Надо бы убрать проверку на user.

2021-12-17 09:14 UTC, intsynko approved these changes

2021-12-28 09:25 UTC, sharifullinildus commented on scenarios/scenario_models/field/field.py
> +        self._masking_fields = user.settings["template_settings"].get("masking_fields") if user is not None else []
Для верности бы лучше передавать в маскинг не пустой массив а прямо None, иначе мы ничего вообще не будем маскировать, ведь дефолтные значения подставляются только для None.

2021-12-28 10:30 UTC, sharifullinildus approved these changes

2022-01-10 07:54 UTC, christinadomanskaya approved these changes

2022-01-10 07:54 UTC, merged