move card check to masking, add counter object to deep mask function,…
sberdevices/smart_app_framework pull request #159
Opened 2021-12-14 13:05 UTC by sharifullinildus

… add mapping to masking_fields

2021-12-15 13:36 UTC, intsynko approved these changes

2021-12-15 14:40 UTC, intsynko commented
Еще думаю стоит накидать тестовых примеров на маскирование карт

2021-12-16 06:52 UTC, sharifullinildus commented
Перенос проверки карты в функцию маскинг, добавлена возможность словаря для маскируемых полей, счетчик для функции глубокой маскировки перенесен в класс

2021-12-16 10:29 UTC, dangerink commented on core/utils/masking_message.py
>          key_gen = enumerate(data)
а как оно не упадет в 117 если тут data: List ?

2021-12-16 11:25 UTC, dangerink approved these changes

2021-12-16 14:15 UTC, intsynko requested changes

2021-12-16 14:25 UTC, intsynko approved these changes

2021-12-16 14:25 UTC, intsynko commented on core/utils/masking_message.py
>          key_gen = enumerate(data)
enumerate отдает (index, value) на каждом этапе итерации - значит data[index] вернет корректное значение

2021-12-16 14:42 UTC, christinadomanskaya approved these changes

2021-12-16 15:42 UTC, merged