Features/customized logger
sberdevices/smart_app_framework pull request #160
Opened 2021-12-14 16:31 UTC by intsynko

1) Добавил  помодульное логирование:
Пример настройки логирования для приложения
 ```yml
loggers:
  your_app:  #  для всего приложения стандартное логирование (как раньше)
    handlers:
      - console_app_handler
      - file_app_handler
    propagate: false
    level: DEBUG
  your_app.app.adapters:  #  для адаптеров внутри приложения - повышаем уровень до ERROR  
    level: ERROR
  smart_kit:  # так же повышаем уровень для smart_kit
    level: ERROR
  core:  # и для core
    level: ERROR
  core.basic_models:  # но в рамках core.basic_models - снова понизим до WARNING
    level: WARNING 
```
Так же можно менять уровень логирования, хэнледры и прочие настройки для каждого модуля, включая стронние библиотеки 
2) Добавил класс LoggerMessageCreator для возможности дополнения и расширения прикидываемых в логи параметров

2021-12-15 07:05 UTC, AivanF commented on smart_kit/template/static/configs/logging_config.yml
> +  {{app_name}}:
Шаблон точно применится? А то в [smart_kit_manager.py](https://github.com/sberdevices/smart_app_framework/blob/3cc964f93e3ccab886f38ba7d8610024ff5f9ed9/smart_kit/management/smart_kit_manager.py#L50) шаблонизация прописана только для файлов с расширением `py-tpl`.

2021-12-15 07:08 UTC, AivanF commented on core/logging/logger_utils.py
>  def _make_message(user=None, params=None, cls_name='', log_store_for=0):
А старая функция осталась на память?)

2021-12-28 09:40 UTC, sharifullinildus requested changes

2021-12-28 09:40 UTC, sharifullinildus commented on smart_kit/management/app_manager.py
> +from core.logging import logger_utils
Импорт без использования

2022-01-10 07:55 UTC, AivanF approved these changes

2022-01-10 07:58 UTC, sharifullinildus approved these changes

2022-01-10 13:04 UTC, merged