Интеграционные поля
sberdevices/smart_app_framework pull request #17
Opened 2020-12-24 15:54 UTC by SokolovVladimir

Добавлены интеграционные поля, которые заполняются только ответом от интеграции. 
Произведено разделение на question и integration поля.
Исправлены ошибки при создании нового аппа.
Испрален template_scenario соответвеноо изменениям.
ToDo - изменить поле required с bool на Requirement

2021-01-14 12:42 UTC, ElephantsFoot requested changes

2021-01-14 12:42 UTC, ElephantsFoot commented on scenarios/scenario_models/field/composite_fillers.py
> +                user: User, params) -> Optional[Union[int, float, str, bool, List, Dict]]:
а это норм менять сигнатуру переопределяемого метода?

2021-01-14 12:42 UTC, ElephantsFoot commented on scenarios/scenario_models/field/composite_fillers.py
> +    #@exc_handler(on_error_obj_method_name="on_extract_error")
не понял зачем нам закомментированный декоратор

2021-01-14 12:42 UTC, ElephantsFoot commented on scenarios/scenario_models/field/field.py
> +        return self._value if self._value is not None else None
какая-то избыточная проверка - "если none, возвращаем none"

2021-01-14 12:42 UTC, ElephantsFoot commented on scenarios/scenario_models/field/field_descriptions/integration_field_description.py
> +        self._retry_count = items.get("retry_count", 0)
проверь, пожалуйста, во всех файлах пустую строку в конце файла

2021-01-14 12:42 UTC, ElephantsFoot commented on smart_kit/resources/__init__.py
> +        field_descriptions[None] = BasicFieldDescription
может нужно сделать по умолчанию как раз QuestionFieldDescription? BasicFieldDescription не может же быть использован в сценарии, на его основе просто будут создавать новые типы филдов.

2021-02-01 11:59 UTC, SokolovVladimir commented on scenarios/scenario_descriptions/form_filling_scenario.py
> +            form = user.forms.new(self.form_type)
Забыл удалить, после дебага

2021-02-01 12:01 UTC, SokolovVladimir commented on scenarios/scenario_models/field/composite_fillers.py
> +                user: User, params) -> Optional[Union[int, float, str, bool, List, Dict]]:
Добавлял Миша Геништа, чтобы в базовые сущности передавались params.
Конечно, правильным было бы везде сделать одинаковую сигнатуру

2021-02-01 12:03 UTC, SokolovVladimir commented on scenarios/scenario_models/field/composite_fillers.py
> +    #@exc_handler(on_error_obj_method_name="on_extract_error")
Уйдет после мерджа конфликтов

2021-02-01 12:05 UTC, SokolovVladimir commented on scenarios/scenario_models/field/field.py
> +        return self._value if self._value is not None else None
Упростил

2021-02-01 12:15 UTC, SokolovVladimir commented on scenarios/scenario_models/field/field_descriptions/integration_field_description.py
> +        self._retry_count = items.get("retry_count", 0)
По диагонали просмотерл core / scenarios / smart_kit добавил пустую строку, где не было

2021-02-01 12:17 UTC, SokolovVladimir commented on smart_kit/resources/__init__.py
> +        field_descriptions[None] = BasicFieldDescription
Да, была такая мысля, и к тому же после аппа не нужно переопределять поведение. Поправил

2021-02-01 12:29 UTC, ElephantsFoot submitted a review, later dismissed

2021-03-31 14:42 UTC, SokolovVladimir commented
Обсудили с Элиша - возник вопрос, может ли интеграционный запрос заполнить несколько полей? Или только одно поле из которого был выполнен запрос?

2021-04-05 11:36 UTC, ElephantsFoot approved these changes

2021-04-08 13:02 UTC, ElephantsFoot approved these changes

2021-04-09 08:58 UTC, nlpfsd approved these changes

2021-04-09 09:03 UTC, merged

2021-04-09 09:26 UTC, dangerink commented on scenarios/scenario_models/field/composite_fillers.py
> +    #@exc_handler(on_error_obj_method_name="on_extract_error")
ну а щас же нет конфликтов а # осталась

2021-04-09 09:26 UTC, dangerink commented on scenarios/scenario_models/field/field.py
> +        return self.value is not None
повторяет базовое поведение, значит можно убрать

2021-04-09 09:26 UTC, dangerink commented on scenarios/scenario_models/field/field_descriptions/integration_field_description.py
> +class IntegrationFieldDescription(BasicFieldDescription):
можно не созавать отдельный класс а просто регистрировать тот же BasicFieldDescription под интеграционным типом

2021-04-09 09:26 UTC, dangerink commented on scenarios/scenario_models/field/field_filler_description.py
> +    # @exc_handler(on_error_obj_method_name="on_extract_error")
не должно остаться закомменченным

2021-04-09 09:29 UTC, dangerink commented on scenarios/scenario_descriptions/form_filling_scenario.py
> -            user.last_scenarios.delete(self.id)
вот это почему было а теперь не нужно, кто-то помнит?