fix DatePeriodFiller
sberdevices/smart_app_framework pull request #171
Opened 2021-12-20 22:55 UTC by Dan1lD

Исправлена логика заполнения филлера

2021-12-21 07:53 UTC, intsynko requested changes

2021-12-21 07:53 UTC, intsynko commented on scenarios/scenario_models/field/field_filler_description.py
> +            'date_period__is_error': str(is_error),
это конечно не твой код, но интересно, тут точно надо к строке булы приводить?

2021-12-23 07:44 UTC, Dan1lD commented on scenarios/scenario_models/field/field_filler_description.py
> +            'date_period__is_error': str(is_error),
Кажется, в этом действительно нет необходимости

2021-12-23 09:58 UTC, intsynko approved these changes

2021-12-23 15:49 UTC, anurmanov approved these changes

2021-12-24 07:22 UTC, merged