disabling specific metrics by matching names
sberdevices/smart_app_framework pull request #172
Opened 2021-12-21 07:22 UTC by intsynko

2021-12-27 08:21 UTC, intsynko commented
обнаружилось два класса мониторинга - в core и smart_kit, поэтому выполняются доработки по объединению их в единый класс мониторинга на базе smart_kit

2021-12-29 06:44 UTC, sharifullinildus approved these changes

2022-01-24 17:57 UTC, SyrexMinus commented
В некоторых случаях может быть не практично матчить метрики только по startwith. Предлагаю сделать матчинг по регулярным выражениям.

2022-01-24 20:19 UTC, SyrexMinus commented on core/monitoring/monitoring.py
>  monitoring = Monitoring()
А эта строка ещё остаётся нужна после удаления импортов?

2022-01-24 20:31 UTC, SyrexMinus commented on tests/core_tests/monitoring_test/test_monitoring.py
> +        counter = self.monitoring.got_counter(event_name)
Точно не get_counter? got_counter никогда не возвращает не none.

2022-01-25 07:11 UTC, dangerink requested changes

2022-01-25 07:11 UTC, dangerink commented on core/monitoring/monitoring.py
> +    def _got_histogram(self, name, description=None):
напутано с модификаторами? зачем тут _ ?

2022-01-25 07:11 UTC, dangerink commented on core/monitoring/monitoring.py
> +    def got_histogram(self, name, description=None):
зачем декоратор? то что убрал в _got_histogram - уже декоратор и контекстный менеджер.

2022-01-25 08:26 UTC, intsynko commented on core/monitoring/monitoring.py
> +    def got_histogram(self, name, description=None):
суть в том, что проверка `if self.check_enabled(name):` выполняется сразу при импорте модулей использующих эту функцию еще до того, как мы прочитаем конфиг и выключим по именам нужных метрики, поэтому понадобился еще один уровень декоратора на котором мы перед непосредственным вызовом декорируемой функции делали проверку `if self.check_enabled(name):` - когда конфиги уже были импортированы и применены

2022-01-25 08:27 UTC, intsynko commented on core/monitoring/monitoring.py
> +    def got_histogram(self, name, description=None):
в качестве оптимизации могу предложить не разделять на два метода, а сделать одним:
```python
    def got_histogram(self, name):
        def decor(func):
            def wrap(*args, **kwargs):
                if self.check_enabled(name):
                    histogram = self._monitoring_items[self.HISTOGRAM]
                    if not histogram.get(name):
                        histogram[name] = Histogram(name, name)
                    return histogram[name].time()(func)(*args, **kwargs)
                else:
                    return func(*args, **kwargs)
            return wrap
        return decor
```

2022-01-25 08:30 UTC, intsynko commented on core/monitoring/monitoring.py
>  monitoring = Monitoring()
много где, но вопрос такой а не объединить ли `Monitoring` и `Metrics` в один класс

2022-01-25 08:36 UTC, intsynko commented on tests/core_tests/monitoring_test/test_monitoring.py
> +        counter = self.monitoring.got_counter(event_name)
скорее всегда возвращает None, но да, тут есть косяк в проверках

2022-01-31 10:50 UTC, intsynko commented on core/monitoring/monitoring.py
>  monitoring = Monitoring()
Дальнейший рефакторинг метрик будет за @AivanF в рамках совместимости с efs навыками

2022-01-31 13:35 UTC, SyrexMinus commented on tests/core_tests/monitoring_test/test_monitoring.py
> +        self.assertEqual(counter_item.get(event_name), None)
Выглядит бесполезно.

2022-01-31 13:46 UTC, SyrexMinus commented on core/monitoring/monitoring.py
> +        metric_disabled = next((True for m in self.disabled_metrics if re.match(m, name)), False)
Лучше 
```suggestion
        metric_disabled = next((True for m in self.disabled_metrics if re.fullmatch(m, name)), False)
```

2022-01-31 13:48 UTC, SyrexMinus requested changes
re.match -> re.fullmatch

2022-01-31 13:58 UTC, intsynko commented on core/monitoring/monitoring.py
> +        metric_disabled = next((True for m in self.disabled_metrics if re.match(m, name)), False)
желательно с пояснением, почему лучше

2022-01-31 14:59 UTC, SyrexMinus approved these changes

2022-02-01 15:57 UTC, dangerink commented on core/monitoring/monitoring.py
> +        metric_disabled = next((True for m in self.disabled_metrics if re.match(m, name)), False)
так и чего в итоге? меняем на fullmatch

2022-02-02 07:23 UTC, intsynko commented on core/monitoring/monitoring.py
> +        metric_disabled = next((True for m in self.disabled_metrics if re.match(m, name)), False)
да, поменяли на fullmatch

2022-02-02 07:48 UTC, dangerink approved these changes

2022-02-02 08:17 UTC, SyrexMinus approved these changes

2022-02-02 08:41 UTC, merged