fix set masking
sberdevices/smart_app_framework pull request #175
Opened 2021-12-23 10:50 UTC by sharifullinildus

2021-12-23 13:09 UTC, intsynko commented
добавь в тесты что правил + добавь описание в пр сверху

2021-12-23 13:52 UTC, intsynko requested changes

2021-12-23 13:52 UTC, intsynko commented on tests/core_tests/masking_test/masking_test.py
> +        self.assertEqual(input_message, expected)
давай еще добавим пример где будем в сете маскировать каждое поле

2021-12-23 13:52 UTC, intsynko commented on tests/core_tests/masking_test/masking_test.py
> +        self.assertEqual(input_message, expected)
сначала excepted потом input

2021-12-23 16:52 UTC, intsynko approved these changes

2021-12-30 07:28 UTC, christinadomanskaya approved these changes

2022-01-10 07:59 UTC, christinadomanskaya approved these changes

2022-01-10 13:38 UTC, merged