Feature/rtdm action
sberdevices/smart_app_framework pull request #178
Opened 2021-12-29 12:05 UTC by SyrexMinus

# rtdm_get и rtdm_send actions.

## Описание:
**rtdm_get**: отправляет POST запрос к сервису _api/v1/search/epkid_ и сохраняет ответ от сервиса в `user.variables["rtdm_get_response"]`.
Пример отправляемого запроса:
 ```
 {
      "rqUid":"5c975471-ecb1-4301-b1ee-a8ddb9de0c3a",
      "rqTm":"20-08-2020T14:05:00",
      "systemName":"nlpSystem",
      "channel":"F",
      "epkId":34234608109,
      "mode":"offerParam,serviceParam"
  }
```
Пример ответа: 
```
{
   "rqUid":"5a999111-eeb1-0001-b1ee-a7ddd9de0c3a",
   "rqTm":"2021-03-04T10:05:00",
   "systemName":"nlpsystem",
   "channel":"F",
   "epkId":"00000000001",
   "offers":[
      {
         "notificationId":"23661232134301",
         "type":"OFFER_BATCH",
         "campaignId":"BC777ABD00",
         "offerKind":"E0110001",
         "priority":1,
         "data":{
            "notificationCode":"Potreb_Credit",
            "V7":"12",
            "V6":"200001",
            "V10":"60",
            "V11":"5340"
         }
      },
      {
         "notificationId":"CMT426111",
         "type":"OFFER_BATCH",
         "campaignId":"BC111ABD66",
         "offerKind":"E0330003",
         "priority":1,
         "data":{
            "notificationCode":"Deposit",
            "V17":"Дополнительный процент",
            "V18":"100 000 ₽",
            "V19":"cрок (3, 6 или 12 месяцев)",
            "V21":"android-app://ru.sberbankmobile/android-app/ru.sberbankmobile/products/deposit?action=create",
            "V20":"sberbankonline://payments/new-deposit?depositType=92&depositGroup=4"
         }
      }
   ],
   "service":[
      {
         "notificationId":"23661232134301",
         "type":"SERVICE_EVENT",
         "campaignId":"BC777ABD00",
         "priority":1,
         "data":{
            "notificationCode":"003",
            "date":1596786406000,
            "amount":1000,
            "currency":"руб",
            "transactionType":6538,
            "transactionRespCode":822,
            "atmNumber":"961072",
            "bin":220056,
            "cardMask":5522
         }
      }
   ],
   "status":{
      "code":0,
      "message":"Успешно"
   }
}
```

**rtdm_send**: Отправка отклика на персональное предложение.
Пример отправляемого запроса:
```
{
     "messageId": 10000001,
     "messageName": "RTDM_VIEWED_EVENTS",
     "userChannel": "SBOL",
     "nextSystem": "RTDM Adapter",
     "handlerName": "AI_HANDLER",
     "userId": "1594098519615",
     "chatId": "1594098487427",
     "notificationId": "1594098519616",
     "notificationCode": "CREDIT",
     "feedbackStatus": "FS",
     "description": "Клик FS"
  }
```

## Использование:
**rtdm_get**:
Обязательное поле `mode` - режим сервиса. Возможные значения:
_offerParam_ - офферы (маркетинговые предложения из Репозитория) с текстом и тегами;
_serviceParam_ - сервисные с тегами;
Пример:
```
{
  "type": "rtdm_get",
  "mode": "offerParam,serviceParam"
}
```

**rtdm_send**:
Обязательное поле `notificationId` - Идентификатор события/ПП по клиенту
Обязательное поле `notificationCode ` - Идентификатор события/ПП отклика
Обязательное поле `feedbackStatus ` - тип фидбэка:
_FS_ - показ ПП в канале ВА,
_FA_ - клиент согласился на условия ПП в канале ВА (использовал саджест или другой аналог), 
_FI_ - клиент прошел по диплинку для оформления,
Опциональное поле `description ` - Дополнительный атрибут
В случае, если feedbackStatus = FA поле следует заполнить названием саджеста или текстом из саджеста
Пример:
```
{
  "type": "rtdm_send",
  "notificationId": "1594098519616",
  "notificationCode": "CREDIT",
  "feedbackStatus": "FS",
  "description": "Клик FS"
}
```

2021-12-29 13:55 UTC, intsynko requested changes

2021-12-29 13:55 UTC, intsynko commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +            "rqTm": datetime.datetime.now().replace(microsecond=0).isoformat(),
now - это местное время, utc_now время по UTC(+0). Нас точно не utc_now нужно?

2021-12-29 13:55 UTC, intsynko commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +    rtdm_get_response.
давай напишем развернуто Пп - персональное предложение
и в названии тоже можно поменять Pp на PersonalOffer
(ну и то же самое со втором action'ом)

2021-12-29 13:55 UTC, intsynko commented on smart_kit/message/smartapp_rtdm_to_message.py
> +        }
description в команде добавляется если он передан в items - тут может быть падение, думаю можно было бы избежать этого так:
```python
fields = {
   "messageId": self.incoming_message.incremental_id,
   "userChannel": self.incoming_message.channel,
   "userId": self.incoming_message.uid,
}
fields.update(self.payload)
```

2021-12-29 13:55 UTC, intsynko commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +            "systemName": user.settings["template_settings"]["system_name"],
думаю в `smart_kit/template/static/configs/template_config.yml` надо добавить `system_name`

2021-12-29 13:55 UTC, intsynko commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +            "rqTm": datetime.datetime.now().replace(microsecond=0).isoformat(),
теоретически здесь можем упасть если время сгенерированное в экшене будет отличаться, можно тоже попробовать запатчить  datetime.datetime.now()

2021-12-29 13:55 UTC, intsynko commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +                                       validators=to_msg_validators).as_dict
думаю `masking_fields` и `to_msg_validators` можно не передавать

2021-12-29 13:55 UTC, intsynko commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +import pytest
не используется

2021-12-29 13:55 UTC, intsynko commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +from core.basic_models.variables.variables import Variables
тоже не используется

2021-12-29 13:55 UTC, intsynko commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +import json
тоже не используется

2021-12-30 07:17 UTC, SyrexMinus commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +    """
Спасибо. Поправил.

2021-12-30 07:17 UTC, SyrexMinus commented on core/basic_models/actions/rtdm_send_response_to_pp_action.py
> +    """
Спасибо. Поправил.

2021-12-30 07:20 UTC, SyrexMinus commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +                }
Почему ты так думаешь?

2021-12-30 07:25 UTC, SyrexMinus commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +            "rqTm": datetime.datetime.now().replace(microsecond=0).isoformat(),
Скорее всего, ты прав. Ведь пользователи могут быть из регионов с разным часовым поясом. Сервис сойдёт с ума если получит запрос из будущего :) Спасибо. Поправил.

2021-12-30 07:38 UTC, SyrexMinus commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +    rtdm_get_response.
Справедливое замечание про название, но я не будет ли лучше сделать Po, а не PersonalOffer, чтобы название укоротить?

2021-12-30 07:45 UTC, SyrexMinus commented on smart_kit/message/smartapp_rtdm_to_message.py
> +        }
Хорошее замечание, но update я бы не стал делать, потому что в сообщение может залететь куча мусора из payload. Можно именно на description сделать if.

2021-12-30 07:59 UTC, SyrexMinus commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +            "systemName": user.settings["template_settings"]["system_name"],
Спасибо. Добавил.

2021-12-30 08:30 UTC, SyrexMinus commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +                                       validators=to_msg_validators).as_dict
Спасибо. Поправил.

2021-12-30 08:32 UTC, SyrexMinus commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +import json
Спасибо. Поправил.

2021-12-30 08:32 UTC, SyrexMinus commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +from core.basic_models.variables.variables import Variables
Спасибо. Поправил.

2021-12-30 08:32 UTC, SyrexMinus commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +import pytest
Спасибо. Поправил.

2021-12-30 09:05 UTC, intsynko commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +                }
смотрел под капотом функцию requests.request

2021-12-30 09:07 UTC, SyrexMinus commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +                "url": "http://localhost:8088/api/v1/search/epkId",
Спасибо. Вынес в template_config.yml в rtdm.url.

2021-12-30 09:11 UTC, intsynko commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +    rtdm_get_response.
Я думаю в таком случае будем гадать как расшифровывается Po, тогда уж лучше Pp - в описании хотя бы расшифровка есть

2021-12-30 09:13 UTC, intsynko commented on smart_kit/message/smartapp_rtdm_to_message.py
> +        }
payload - это command_params который формируется в экшене - так что мусора там не будет

2021-12-30 09:14 UTC, intsynko commented on tests/core_tests/basic_scenario_models_test/action_test/test_action.py
> +            "rqTm": datetime.datetime.now().replace(microsecond=0).isoformat(),
Пока хз как править - патчить коробочный тип питон не дает

2021-12-30 10:37 UTC, SyrexMinus commented
Надо ещё реализовать легирование. В логах доступна следующая информация:
URL запроса
Тело запроса
Тип запроса (POST, GET)
Статус запроса
Время затраченное на запрос
Тело ответа

2021-12-30 10:37 UTC, SyrexMinus commented
Надо сделать настройки skillflow.plugins.kafka.config.producers.config.bootstrap_servers - Настройка брокеров для отправки откликов в RTDM

2021-12-30 10:38 UTC, SyrexMinus commented
Надо реализовать универсальный транспортный filler для REST запросов к сервисам RTDM: "type": "rtdm_info_request_filler"
Данный action получает ЕПК ID из MESSAGE_TO_SKILL (RUN_APP/SERVER_ACTION) формирует и выполняет POST запрос согласно контракта
Возвращает полученный ответ без изменения в навык

2021-12-30 10:39 UTC, SyrexMinus commented
Надо удостовериться, что реализован универсальный транспортный action отправки откликов в RTDM

2021-12-30 10:39 UTC, SyrexMinus commented
Надо реализовать стандартные метрики мониторинга

2022-01-10 04:55 UTC, SyrexMinus commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +                }
Спасибо. Поправил.

2022-01-10 04:59 UTC, SyrexMinus commented on core/basic_models/actions/rtdm_get_pp_and_events_action.py
> +    rtdm_get_response.
Спасибо. Оставил Pp

2022-01-10 05:03 UTC, SyrexMinus commented on smart_kit/message/smartapp_rtdm_to_message.py
> +        }
Спасибо. Поправил.

2022-01-14 12:58 UTC, intsynko commented
Решено вынести этот функционал в отдельный плагин saf_banking

2022-01-14 12:58 UTC, closed without merging