Feature/rtdm support
sberdevices/smart_app_framework pull request #183
Opened 2022-01-12 06:12 UTC by SyrexMinus

# rtdm_get и rtdm_send actions.

## Описание:
**rtdm_get**: отправляет POST запрос к сервису _api/v1/search/epkid_ и сохраняет ответ от сервиса в `user.variables["rtdm_get_response"]`.
Пример отправляемого запроса:
 ```
 {
      "rqUid":"5c975471-ecb1-4301-b1ee-a8ddb9de0c3a",
      "rqTm":"20-08-2020T14:05:00",
      "systemName":"nlpSystem",
      "channel":"F",
      "epkId":34234608109,
      "mode":"offerParam,serviceParam"
  }
```
Пример ответа: 
```
{
   "rqUid":"5a999111-eeb1-0001-b1ee-a7ddd9de0c3a",
   "rqTm":"2021-03-04T10:05:00",
   "systemName":"nlpsystem",
   "channel":"F",
   "epkId":"00000000001",
   "offers":[
      {
         "notificationId":"23661232134301",
         "type":"OFFER_BATCH",
         "campaignId":"BC777ABD00",
         "offerKind":"E0110001",
         "priority":1,
         "data":{
            "notificationCode":"Potreb_Credit",
            "V7":"12",
            "V6":"200001",
            "V10":"60",
            "V11":"5340"
         }
      },
      {
         "notificationId":"CMT426111",
         "type":"OFFER_BATCH",
         "campaignId":"BC111ABD66",
         "offerKind":"E0330003",
         "priority":1,
         "data":{
            "notificationCode":"Deposit",
            "V17":"Дополнительный процент",
            "V18":"100 000 ₽",
            "V19":"cрок (3, 6 или 12 месяцев)",
            "V21":"android-app://ru.sberbankmobile/android-app/ru.sberbankmobile/products/deposit?action=create",
            "V20":"sberbankonline://payments/new-deposit?depositType=92&depositGroup=4"
         }
      }
   ],
   "service":[
      {
         "notificationId":"23661232134301",
         "type":"SERVICE_EVENT",
         "campaignId":"BC777ABD00",
         "priority":1,
         "data":{
            "notificationCode":"003",
            "date":1596786406000,
            "amount":1000,
            "currency":"руб",
            "transactionType":6538,
            "transactionRespCode":822,
            "atmNumber":"961072",
            "bin":220056,
            "cardMask":5522
         }
      }
   ],
   "status":{
      "code":0,
      "message":"Успешно"
   }
}
```

**rtdm_send**: Отправка отклика на персональное предложение.
Пример отправляемого запроса:
```
{
     "messageId": 10000001,
     "messageName": "RTDM_VIEWED_EVENTS",
     "userChannel": "SBOL",
     "nextSystem": "RTDM Adapter",
     "handlerName": "AI_HANDLER",
     "userId": "1594098519615",
     "chatId": "1594098487427",
     "notificationId": "1594098519616",
     "notificationCode": "CREDIT",
     "feedbackStatus": "FS",
     "description": "Клик FS"
  }
```

## Использование:
**rtdm_get**:
Обязательное поле `mode` - режим сервиса. Возможные значения:
_offerParam_ - офферы (маркетинговые предложения из Репозитория) с текстом и тегами;
_serviceParam_ - сервисные с тегами;
Пример:
```
{
  "type": "rtdm_get",
  "mode": "offerParam,serviceParam"
}
```

**rtdm_send**:
Обязательное поле `notificationId` - Идентификатор события/ПП по клиенту
Обязательное поле `notificationCode` - Идентификатор события/ПП отклика
Обязательное поле `feedbackStatus` - тип фидбэка:
_FS_ - показ ПП в канале ВА,
_FA_ - клиент согласился на условия ПП в канале ВА (использовал саджест или другой аналог), 
_FI_ - клиент прошел по диплинку для оформления,
Опциональное поле `description` - Дополнительный атрибут
В случае, если feedbackStatus = FA поле следует заполнить названием саджеста или текстом из саджеста
Пример:
```
{
  "type": "rtdm_send",
  "notificationId": "1594098519616",
  "notificationCode": "CREDIT",
  "feedbackStatus": "FS",
  "description": "Клик FS"
}
```

2022-01-12 07:47 UTC, intsynko requested changes

2022-01-12 07:47 UTC, intsynko commented on smart_kit/template/static/configs/template_config.yml
> +system_name: framework_smartapp_system_name
Это точно тут надо оставить? Если это нужно только конкретному экшену в отдельном плагине - то может тогда в экшене прописать что надо в `template_config.yml` добавить эти настройки?

2022-01-12 08:01 UTC, SyrexMinus commented on smart_kit/template/static/configs/template_config.yml
> +system_name: framework_smartapp_system_name
ладно, испортим жизнь тем, кто будет использовать плагин))))

2022-01-13 08:20 UTC, intsynko commented on smart_kit/template/static/configs/template_config.yml
> +system_name: framework_smartapp_system_name
тык что, будем портить?)

2022-01-17 05:15 UTC, SyrexMinus commented on smart_kit/template/static/configs/template_config.yml
> +system_name: framework_smartapp_system_name
да, почему бы и нет

2022-01-20 13:03 UTC, AivanF commented on smart_kit/message/get_message_handler.py
> +message_handlers = Registered()
Предлагаю во избежание путаницы переименовать эту сущность, ведь классы рода `ToMessage` это не совсем хандлеры, они вроде ничего не обрабатывают, а конкретно хандлеры у нас уже есть и это совсем другие классы.

2022-01-20 19:39 UTC, SyrexMinus commented on smart_kit/message/get_message_handler.py
> +message_handlers = Registered()
Переименовал, посмотри

2022-01-21 13:20 UTC, intsynko requested changes

2022-01-21 13:20 UTC, intsynko commented on smart_kit/message/get_to_message.py
> +def get_to_message(command_name):
тогда get_to_message_class

2022-01-21 13:20 UTC, intsynko commented on smart_kit/message/get_to_message.py
> +to_messages = Registered()
и to_message_classes

2022-01-24 05:35 UTC, SyrexMinus commented on smart_kit/message/get_to_message.py
> +to_messages = Registered()
У нас во фрейме есть пример аналогичного дикта, который не содержит в себе classes (actions и другие переменные в resources)

2022-01-24 05:35 UTC, SyrexMinus commented on smart_kit/message/get_to_message.py
> +def get_to_message(command_name):
У нас во фрейме есть пример аналогичного дикта, который не содержит в себе classes (actions и другие переменные в resources)

2022-01-25 08:04 UTC, intsynko approved these changes

2022-01-25 13:26 UTC, AivanF approved these changes

2022-01-25 13:34 UTC, merged