change type check for default list and dict
sberdevices/smart_app_framework pull request #184
Opened 2022-01-12 06:36 UTC by sharifullinildus

2022-01-12 10:06 UTC, intsynko requested changes

2022-01-12 10:06 UTC, intsynko commented on core/utils/masking_message.py
> +    return isinstance(value, dict) or isinstance(value, list) and not isinstance(value, str)
тут может достаточно проверки `isinstance(value, (dict, list))`, строка точно не лист или дикт

2022-01-12 10:06 UTC, intsynko commented on core/utils/masking_message.py
> +def masking(data: Union[dict, list], masking_fields: Optional[Union[dict, list]] = None,
В аргументах функции я бы оставил типы из typing: `list->List`, `dict->Dict`

2022-01-12 10:07 UTC, intsynko commented
Добавь еще плиз описание на русском: что сделано и почему так сделано

2022-01-12 12:55 UTC, intsynko commented
У меня есть еще мыcли по поводу сокращения времени обработки: перед маскингом мы делаем глубокую копию полностью обходя объект а потом еще раз при маскировании. Было бы быстрее если маскирование само создавало новый дикт и по ходу маскирования дополняла его

2022-01-13 08:19 UTC, intsynko approved these changes

2022-01-25 15:13 UTC, SyrexMinus approved these changes

2022-01-27 07:35 UTC, intsynko requested changes

2022-01-27 07:35 UTC, intsynko commented on core/utils/masking_message.py
>          if isinstance(data[key], set):
давай тут еще кроме set будем tuple поддерживать и тоже приводить к листу?

2022-01-28 06:55 UTC, sharifullinildus commented on core/utils/masking_message.py
>          if isinstance(data[key], set):
Done

2022-01-30 08:14 UTC, intsynko approved these changes

2022-02-09 11:32 UTC, dangerink approved these changes

2022-02-09 11:33 UTC, merged