fix logger error
sberdevices/smart_app_framework pull request #186
Opened 2022-01-13 11:50 UTC by intsynko

Сделал обработку исключения отсутствия app_config.

Это нужно, потому что тесты не падали, но при этом был рейс:
```python
Failed to write a log. Exception occurred
Traceback (most recent call last):
  File "/Users/out-intsyn-ko/PycharmProjects/smart_app_framework/core/logging/logger_utils.py", line 72, in log
    message_maker = get_app_config().LOGGER_MESSAGE_CREATOR
  File "/Users/out-intsyn-ko/PycharmProjects/smart_app_framework/smart_kit/configs/__init__.py", line 36, in get_app_config
    app_config = importlib.import_module(app_config)
  File "/Users/out-intsyn-ko/.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Рейс из за того что аппы должны иметь свой app_config, адрес на который должны прописать в переменные среды. Тесты в переменных среды адрес на конфиг не задают, так как не имеют его - поэтому и происходит рейс.

2022-01-13 12:00 UTC, Dan1lD submitted a review, later dismissed

2022-01-17 07:00 UTC, dangerink commented on core/logging/logger_utils.py
> +        params = masking(pickle_deepcopy(params))
percent_fix все таки был нужен, может его в masking перенести.
он позволяет не падать если в мессадж окажется  http://xx.x?some%20value

2022-01-17 07:06 UTC, intsynko commented on core/logging/logger_utils.py
> +        params = masking(pickle_deepcopy(params))
Его захардкодить в маскинг или добавить было ссылку на функцию, которой обрабатываем в маскинге строку?

2022-01-17 07:08 UTC, dangerink commented on core/logging/logger_utils.py
> +        params = masking(pickle_deepcopy(params))
добавить функцию в логутилс, т.к. это про логи, не про маскинг(он же не только для логов)

2022-01-17 09:24 UTC, Dan1lD submitted a review, later dismissed

2022-01-17 10:18 UTC, dangerink submitted a review, later dismissed

2022-01-17 12:16 UTC, dangerink submitted a review, later dismissed

2022-01-17 12:21 UTC, Dan1lD submitted a review, later dismissed

2022-01-18 06:58 UTC, dangerink approved these changes

2022-01-18 07:03 UTC, dangerink requested changes
def escape(cls, string):
нужно оптимизировать

2022-01-20 07:52 UTC, Dan1lD approved these changes

2022-01-20 10:10 UTC, dangerink approved these changes

2022-01-20 10:10 UTC, merged