Add exception catch for ignite adapter save and get cache
sberdevices/smart_app_framework pull request #188
Opened 2022-01-21 08:25 UTC by sharifullinildus

Добавлены ловля ошибки при сохранении и получении кэша в игнайт адаптере

2022-01-21 10:55 UTC, intsynko requested changes

2022-01-21 10:55 UTC, intsynko commented on core/db_adapter/ignite_adapter.py
> +            return data
можно сразу return self.cahce.get(id)

2022-01-21 10:55 UTC, intsynko commented on core/db_adapter/ignite_adapter.py
> +        except Exception:
а может надо ловить какую нибудь конкретную которая падали при попытке что то взять?

2022-01-21 10:55 UTC, intsynko commented on core/db_adapter/ignite_adapter.py
> +            return data
не вызовет ли других ошибок то, что мы при вызове этого метода в ответ можем получить `None`? Мб сделать обработку везде где вызываем?

2022-01-25 12:25 UTC, sharifullinildus commented on core/db_adapter/ignite_adapter.py
> +            return data
Done

2022-01-25 12:25 UTC, sharifullinildus commented on core/db_adapter/ignite_adapter.py
> +        except Exception:
Done

2022-01-25 13:20 UTC, intsynko submitted a review, later dismissed

2022-01-25 15:06 UTC, SyrexMinus approved these changes

2022-01-25 16:09 UTC, dangerink commented on core/db_adapter/ignite_adapter.py
> +            )
+ raise

2022-01-25 16:09 UTC, dangerink commented on core/db_adapter/ignite_adapter.py
> +
+ raise

2022-01-25 16:10 UTC, dangerink commented on core/db_adapter/ignite_adapter.py
> +CacheError = pyignite.exceptions.CacheError
зачем? достаточно импортнуть

2022-01-25 16:29 UTC, dangerink requested changes

2022-01-25 16:29 UTC, dangerink commented on core/db_adapter/ignite_adapter.py
> +            )
вообще, видимо это ничего не даст, т.к. CacheError должен был быть пойман внешним try-except и написаться в лог

+в методе  replace_if_equals забыл добавить

2022-01-26 09:41 UTC, sharifullinildus commented on core/db_adapter/ignite_adapter.py
> +        except CacheError:
Done

2022-01-26 09:41 UTC, sharifullinildus commented on core/db_adapter/ignite_adapter.py
> +            )
Done

2022-01-26 09:41 UTC, sharifullinildus commented on core/db_adapter/ignite_adapter.py
> +
Done

2022-01-26 09:42 UTC, sharifullinildus commented on core/db_adapter/ignite_adapter.py
> +CacheError = pyignite.exceptions.CacheError
Done

2022-03-09 06:48 UTC, SyrexMinus commented on core/db_adapter/ignite_thread_adapter.py
> +        except (HandshakeError, ReconnectError):
Можно добавить ConnectionError из client.connect->_process_connect_args.

2022-03-09 07:07 UTC, SyrexMinus commented
Для AsyncIgniteAdapter не надо то же самое сделать?

2022-03-09 07:22 UTC, intsynko commented on core/db_adapter/ignite_thread_adapter.py
> +        except (HandshakeError, ReconnectError):
мб есть что то базовое для них всех?

2022-03-10 13:39 UTC, closed without merging