DPNLPF: logging fixes for log storing update
sberdevices/smart_app_framework pull request #190
Opened 2022-01-26 13:21 UTC by sharifullinildus

Изменение логов для регулировки срока хранения

2022-02-04 11:10 UTC, intsynko requested changes

2022-02-04 11:10 UTC, intsynko commented on core/logging/logger_utils.py
> +        log_store_for = logging.log_store_for_map.get(params.get(log_const.KEY_NAME, {}), log_store_for)
1) `params.get(log_const.KEY_NAME, {})` если не нашли ключ - то по дефолту не пустой словарь, а пусть будет None, потому что мы его используем как ключ дальше (`params.get(log_const.KEY_NAME, {})` -> `params.get(log_const.KEY_NAME) `)
2) В тестах мы не вызываем  init_logging() - поэтому logging.log_store_for_map будет падать, поэтому предлагаю брать этот атрибут через функцию `getattr`
3) log_store_for пришедший в функцию думаю должен быть в приоритете над конфигом, для этого предлагаю поставить дефолтное значение log_store_for в функции как None и проверять так:
```python
        if log_store_for is None:
            log_store_for = getattr(logging, 'log_store_for_map', {}).get(params.get(log_const.KEY_NAME)) or 0
```

2022-02-04 14:16 UTC, sharifullinildus commented on core/logging/logger_utils.py
> +        log_store_for = logging.log_store_for_map.get(params.get(log_const.KEY_NAME, {}), log_store_for)
Done

2022-02-08 08:05 UTC, intsynko submitted a review, later dismissed

2022-02-09 10:45 UTC, dangerink commented on core/model/base_user.py
> +    def raw_without_log(self):
может просто убрать лог во вне, где где он нужен, а не плодить методы с логом и без?

2022-02-09 10:47 UTC, dangerink commented on smart_kit/start_points/main_loop_kafka.py
> +            params={log_const.KEY_NAME: "outgoing_message" + request.topic_key,
- лучше через форматирование строки
- нет разделителя 
- не всегда задан topic_key, иногда его нет, есть только request.topic

2022-02-09 10:49 UTC, dangerink requested changes
см. [smart_kit/start_points/main_loop_kafka.py]

2022-02-10 05:58 UTC, sharifullinildus commented on smart_kit/start_points/main_loop_kafka.py
> +            params={log_const.KEY_NAME: "outgoing_message" + request.topic_key,
Done

2022-02-10 05:58 UTC, sharifullinildus commented on core/model/base_user.py
> +    def raw_without_log(self):
Done

2022-02-14 09:57 UTC, intsynko approved these changes

2022-02-14 11:57 UTC, dangerink commented on smart_kit/start_points/base_main_loop.py
> -                            "user_length": len(str_data)})
user_length договорились убрать в другое место, а не выпилить

2022-02-14 11:57 UTC, dangerink requested changes
вопрос про user_length

2022-02-22 10:50 UTC, christinadomanskaya commented on smart_kit/start_points/base_main_loop.py
> -                            "user_length": len(str_data)})
оно в base_user уехало

2022-02-22 10:50 UTC, christinadomanskaya approved these changes

2022-02-22 10:58 UTC, dangerink approved these changes

2022-02-22 10:58 UTC, merged