поддержка rtdm_send action и rtdm_info_request_filler
sberdevices/smart_app_framework pull request #191
Opened 2022-01-26 19:06 UTC by SyrexMinus

add kafka constant

2022-01-28 07:30 UTC, intsynko requested changes

2022-01-28 07:30 UTC, intsynko commented on core/configs/global_constants.py
> +KAFKA = "kafka"
думаю в `CommandActions.DEFAULT_REQUEST_TYPE` надо поменять значение со стоки на эту константу

2022-01-28 07:44 UTC, SyrexMinus commented on core/configs/global_constants.py
> +KAFKA = "kafka"
Done.

2022-01-30 08:11 UTC, intsynko approved these changes

2022-01-31 15:17 UTC, merged