draft: Поправить пакетный прогон для возможности проверки рандомного ответа
sberdevices/smart_app_framework pull request #192
Opened 2022-01-27 06:19 UTC by SyrexMinus

check answers in testsuite by regex

Надо ещё тесты в template аппе поправить.

2022-02-04 11:35 UTC, intsynko requested changes

2022-02-04 11:35 UTC, intsynko commented on smart_kit/utils/diff.py
> +    if expected != actual and not re.fullmatch(expected, actual):
Более узкая проверка `expected != actual` входит в более широкую `not re.fullmatch(expected, actual)` - по логике дискретной математики более узкая сокращается

2022-02-08 08:04 UTC, SyrexMinus commented on smart_kit/utils/diff.py
> +    if expected != actual and not re.fullmatch(expected, actual):
Опровергающий твою гипотезу пример: fullmatch("Что вы сказали?", "Что вы сказали?"). Регулярки делают некоторые символы специальными, из-за чего матч может не проходить.

Возможно, может появится вопрос зачем тогда оставлять `expected != actual`. Ответ: чтобы поддержать старые тесты.

2022-02-08 08:08 UTC, intsynko commented on smart_kit/utils/diff.py
> +    if expected != actual and not re.fullmatch(expected, actual):
Ога, согласен

2022-02-08 08:09 UTC, intsynko approved these changes

2022-02-09 08:14 UTC, Dan1lD approved these changes

2022-02-09 08:18 UTC, christinadomanskaya approved these changes

2022-02-09 08:19 UTC, merged