client_profile_actions
sberdevices/smart_app_framework pull request #193
Opened 2022-01-27 11:09 UTC by Dan1lD

2022-01-28 06:37 UTC, SyrexMinus commented
Чтобы акшны работали, их нужно зарегистрировать в *smart_kit/resources/__init__.py* в функции `init_actions`.

2022-01-28 06:38 UTC, SyrexMinus commented
Ещё было бы хорошо протестировать акшны в реальном аппе.

2022-01-28 06:39 UTC, SyrexMinus commented
И ещё надо бы написать тесты для акшнов для поддерживаемости кода.

2022-01-28 06:41 UTC, SyrexMinus requested changes
Чтобы акшны работали, их нужно зарегистрировать в *smart_kit/resources/\_\_init\_\_.py* в функции `init_actions`.

2022-01-28 06:41 UTC, SyrexMinus requested changes
Ещё было бы хорошо протестировать акшны в реальном аппе.

2022-01-28 15:07 UTC, christinadomanskaya commented on core/basic_models/actions/client_profile_actions.py
> +                "memoryPartition": "confidentialMemo",
может эту структуру хлопнуть в {"confidentialMemo": [список тэгов], "projectPrivateMemo": ["character_{{message.uuid.userId}}"]} ?

2022-01-28 15:07 UTC, christinadomanskaya commented on core/basic_models/actions/client_profile_actions.py
> +      "clientIds": {
его можно прям в коде задать, есть во входящем сообщении

2022-01-31 12:59 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +                "memoryPartition": "confidentialMemo",
done

2022-01-31 15:26 UTC, SyrexMinus commented on core/basic_models/actions/client_profile_actions.py
> +    """
```suggestion
    """
    Example::
```

2022-02-01 07:49 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +      "clientIds": {
done

2022-02-04 08:10 UTC, intsynko requested changes

2022-02-04 08:10 UTC, intsynko commented on core/basic_models/actions/client_profile_actions.py
> +        command_params = self._generate_command_context(user, text_preprocessing_result, params)
начиная с этой строчки идет дублирование логики наследуемого класса `StringAction` - предлагаю тут вызвать `super().run(user, text_preprocessing_result, params)` проставив в этом методе `self.request_type = KAFKA` (заодно заюзать константу)

2022-02-04 08:10 UTC, intsynko commented on core/basic_models/actions/client_profile_actions.py
> +        command_params = self._generate_command_context(user, text_preprocessing_result, params)
Тут тоже дублирование логики из `StringAction`

2022-02-04 09:53 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +            self._nodes["memory"].append({"memoryPartition": key, "tags": val})
done

2022-02-04 09:53 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +        command_params = self._generate_command_context(user, text_preprocessing_result, params)
done

2022-02-04 09:53 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +        command_params = self._generate_command_context(user, text_preprocessing_result, params)
done

2022-02-04 11:37 UTC, intsynko commented on core/basic_models/actions/client_profile_actions.py
>          return commands
`return super().run(user, text_preprocessing_result, params)` и ниже тоже

2022-02-09 07:48 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
>          return commands
мне кажется, что для читабельности кода лучше оставить `commands`

2022-02-09 13:21 UTC, christinadomanskaya approved these changes

2022-02-09 13:40 UTC, sharifullinildus approved these changes

2022-02-09 13:46 UTC, dangerink submitted a review, later dismissed

2022-02-09 13:47 UTC, intsynko approved these changes

2022-02-09 14:08 UTC, dangerink submitted a review, later dismissed

2022-02-09 17:54 UTC, SyrexMinus commented on core/basic_models/actions/client_profile_actions.py
> +KAFKA = "kafka"
Дублирует `from core.configs.global_constants import KAFKA`

2022-02-09 17:56 UTC, SyrexMinus commented on core/basic_models/actions/client_profile_actions.py
> +    example: {
дублируется

2022-02-10 07:26 UTC, SyrexMinus commented on core/basic_models/actions/client_profile_actions.py
> +            "kafka_key": self.DEFAULT_KAFKA_KEY,
Папы не могут иметь другого kafka_key, помимо "main"?

2022-02-10 07:27 UTC, SyrexMinus commented on core/basic_models/actions/client_profile_actions.py
> +            "kafka_key": self.DEFAULT_KAFKA_KEY,
Аппы не могут иметь другого kafka_key, помимо "main"?

2022-02-10 07:31 UTC, SyrexMinus commented on core/basic_models/actions/client_profile_actions.py
> +        items["command"] = GIVE_ME_MEMORY
Я бы сделал проще: назначил бы self.command после `super().__init__(items, id)`.

2022-02-10 07:31 UTC, dangerink commented on core/basic_models/actions/client_profile_actions.py
> +    Example::
в чем прикол?
 Example::
     example:

2022-02-10 08:30 UTC, intsynko commented on core/basic_models/actions/client_profile_actions.py
> +    Example::
это я закосячил с саджестами, но надеюсь @Dan1lD поправит

2022-02-10 11:40 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +    Example::
done

2022-02-10 11:47 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +        items["command"] = GIVE_ME_MEMORY
код не выполнится (см.  `__init__` у CommandAction

2022-02-10 11:48 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +            "kafka_key": self.DEFAULT_KAFKA_KEY,
нет

2022-02-10 11:48 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +            "kafka_key": self.DEFAULT_KAFKA_KEY,
нет

2022-02-14 07:39 UTC, intsynko approved these changes

2022-02-14 07:44 UTC, christinadomanskaya approved these changes

2022-02-14 07:45 UTC, merged