Removed nested level of message in HttpTextNormalizer
sberdevices/smart_app_framework pull request #194
Opened 2022-02-01 08:17 UTC by justanotheruser

2022-02-04 07:13 UTC, intsynko approved these changes

2022-02-08 03:51 UTC, sharifullinildus approved these changes

2022-02-08 09:01 UTC, christinadomanskaya approved these changes

2022-02-08 09:11 UTC, intsynko requested changes
Не понял суть бага, потому что ПР, в котором он создан никак не менял ответ метода. Можешь объяснить?

P.S. понял суть бага, ответ действительно менялся

2022-02-14 10:51 UTC, intsynko commented on smart_kit/text_preprocessing/http_text_normalizer.py
> -            raise NormalizationError(f"Malformed Message Received: {batch}")
в данном случае обработка вообще убрана и на уровне `result = [item["message"] for item in response.json()]` будет рейситься `KeyError: key 'message' not found`. Есть ли разница что будет рейситься в этом месте?

2022-02-14 10:51 UTC, intsynko approved these changes

2022-02-21 10:49 UTC, merged