UFS Monitoring
sberdevices/smart_app_framework pull request #197
Opened 2022-02-03 13:08 UTC by bart02

2022-02-15 08:05 UTC, AivanF requested changes

2022-02-17 08:50 UTC, intsynko commented
А почему мы в асинк льем, а не в мастер?

2022-02-17 08:51 UTC, intsynko reviewed
А почему мы в асинк льем, а не в мастер?

2022-02-17 08:52 UTC, AivanF commented
> А почему мы в асинк льем, а не в мастер?

Потому что ПР сделали до того, как асинк влили в мастер, он ещё не поправлен `:)`

2022-04-04 08:48 UTC, closed without merging