improve client_profile_actions
sberdevices/smart_app_framework pull request #203
Opened 2022-02-17 08:08 UTC by Dan1lD

Добавлена возможность задавать kafka_key для client_profile в конфиге или в параметрах экшна

2022-02-17 08:15 UTC, intsynko requested changes

2022-02-17 08:15 UTC, intsynko commented on core/basic_models/actions/client_profile_actions.py
> +        self.kafka_key = items.get("kafka_key")
Мне кажется лучше в одном месте выбирать
```python
settings_kafka_key = user.settings["template_settings"].get("clientId_profile_kafka_key")
self.kafka_key = items.get("kafka_key") or settings_kafka_key or self.DEFAULT_KAFKA_KEY
```

2022-02-17 08:28 UTC, dangerink commented on core/basic_models/actions/client_profile_actions.py
> +        self.kafka_key = items.get("kafka_key")
и лучше если в ините, нет же необхожимости на run это прогонять

2022-02-17 09:01 UTC, Dan1lD commented on core/basic_models/actions/client_profile_actions.py
> +        self.kafka_key = items.get("kafka_key")
в инит не передаётся юзер, а в run не передаются items

2022-02-18 08:16 UTC, intsynko commented on core/basic_models/actions/client_profile_actions.py
> +        settings_kafka_key = self.kafka_key = user.settings["template_settings"].get("client_profile_kafka_key")
чето тут намудрил

2022-02-22 08:00 UTC, intsynko approved these changes

2022-02-22 08:05 UTC, christinadomanskaya approved these changes

2022-02-22 08:09 UTC, AivanF approved these changes

2022-02-22 08:20 UTC, merged