unify http request and base http
sberdevices/smart_app_framework pull request #209
Opened 2022-02-28 09:48 UTC by intsynko

Объединил HTTPRequestAction и BaseHTTPRequestAction на основе HTTPRequestAction.

Это нужно для того чтобы не изменять структуру ответа и оставить её единой для всех экшенов (BaseHTTPRequestAction возвращал ответ, а в сигнатуре метода run у всех экешенов: Optional[List[Command]]).

2022-03-15 13:16 UTC, SyrexMinus commented on smart_kit/action/http.py
>          behavior_description = user.descriptions["behaviors"][self.behavior]
По-моему, если не указать в `items` `behavior`, то эта строчка уронит апп.

Возможный фикс:
```suggestion
        behavior_description = user.descriptions["behaviors"].get(self.behavior)
```

2022-03-15 13:36 UTC, SyrexMinus commented on smart_kit/action/http.py
> +        self.method_params.setdefault("timeout", behavior_description.timeout(user))
А если self.behavior не указан? Вызов атрибута timeout от None?

2022-03-15 13:54 UTC, SyrexMinus requested changes
Всё ок, но нужен тест на случай, когда не указан behavior.

2022-03-18 10:56 UTC, SyrexMinus approved these changes

2022-04-12 13:07 UTC, christinadomanskaya approved these changes

2022-04-12 13:07 UTC, merged