DPNLPF-1570: remove text_preprocessing_result from handlers that do not have message
sberdevices/smart_app_framework pull request #227
Opened 2022-03-24 17:21 UTC by SyrexMinus

Убрал создание и передачу text_preprocessing_result из handlers, которые не имеют message.

Таким образом, handlers не будут логировать бесполезную информацию о тексте, которого не может быть, а также не будут тратить время на создание объектов TextPreprocessingResult.

2022-03-24 17:31 UTC, dangerink commented on smart_kit/handlers/handler_text.py
>          answer = self._handle_base(text_preprocessing_result, user)
тут это же дойдет до всех экшенов, значит везде надо тип указать как Optional

2022-03-25 08:09 UTC, dangerink commented on smart_kit/handlers/handle_close_app.py
> +            log("HandlerCloseApp without text preprocessing result", user, params)
давай не пложить разные логи. достаточно оставить один текст и либо добавлять либо нет params["tpr_str"]

2022-03-27 13:02 UTC, SyrexMinus commented on smart_kit/handlers/handler_text.py
>          answer = self._handle_base(text_preprocessing_result, user)
Решили выпилить только логи, TPR будет передаваться всегда не None.

2022-03-27 13:06 UTC, SyrexMinus commented on smart_kit/handlers/handle_close_app.py
> +            log("HandlerCloseApp without text preprocessing result", user, params)
Done.

2022-03-30 09:19 UTC, dangerink approved these changes, later dismissed

2022-04-01 07:58 UTC, intsynko requested changes

2022-04-01 07:58 UTC, intsynko commented on smart_kit/handlers/handler_text.py
> +        if payload.get("message"):
давай не проверять, он всегда тут должен быть, глобальный трай эксепт это должен обработать

2022-04-01 08:09 UTC, SyrexMinus commented on smart_kit/handlers/handler_text.py
> +        if payload.get("message"):
Done.

2022-04-12 11:04 UTC, intsynko approved these changes

2022-04-12 12:33 UTC, merged