remove second pickle_deepcopy
sberdevices/smart_app_framework pull request #231
Opened 2022-04-06 07:58 UTC by Dan1lD

удаляет дубликат функции pickle_deepcopy

2022-04-06 08:01 UTC, intsynko approved these changes

2022-04-06 08:02 UTC, bart02 commented
В dp есть пара использований `smart_kit.utils.pickle_copy`, посмотри пж. И еще возможно какие-то аппы на него подвязались.

2022-04-07 18:02 UTC, SyrexMinus approved these changes

2022-04-07 18:04 UTC, SyrexMinus commented
> В dp есть пара использований `smart_kit.utils.pickle_copy`, посмотри пж. И еще возможно какие-то аппы на него подвязались.

Когда приложения будут переезжать на новую версию фреймворка, они могут пофиксить это.

2022-04-07 18:06 UTC, SyrexMinus requested changes
Добавь в ридми коммент для тех, кто будет обновляться, чтобы поменяли импорт `smart_kit.utils.pickle_copy` на `core.utils.pickle_copy`

2022-04-11 13:46 UTC, intsynko reviewed
а мне кажется достаточно будет в релизе написать

2022-04-11 14:42 UTC, SyrexMinus approved these changes

2022-04-12 11:51 UTC, christinadomanskaya approved these changes

2022-04-12 11:51 UTC, merged