Added ThreadPoolExecutor
sberdevices/smart_app_framework pull request #39
Opened 2021-02-01 20:55 UTC by AivanF

2021-02-02 14:47 UTC, ElephantsFoot requested changes

2021-02-02 14:47 UTC, ElephantsFoot commented on smart_kit/start_points/main_loop_async_http.py
> +        max_workers = self.settings.get("max_workers", (os.cpu_count() or 1) * 5)
ты здесь обращаешься к settings раньше чем они проинициализируются в родительском классе

2021-02-02 14:47 UTC, ElephantsFoot commented on smart_kit/start_points/main_loop_async_http.py
> +        max_workers = self.settings.get("max_workers", (os.cpu_count() or 1) * 5)
если ты предполагаешь, что max_workers лежат в template_config.yaml, то обращаться нужно settings["template_settings"]

2021-02-02 20:31 UTC, ElephantsFoot approved these changes

2021-02-04 14:03 UTC, dangerink approved these changes

2021-02-08 10:03 UTC, dangerink approved these changes

2021-02-12 13:58 UTC, nlpfsd approved these changes

2021-02-13 07:40 UTC, merged