intersection requirement
sberdevices/smart_app_framework pull request #55
Opened 2021-02-24 13:11 UTC by ElephantsFoot

add intersection requirement

2021-02-24 13:25 UTC, nlpfsd requested changes

2021-02-24 13:25 UTC, nlpfsd commented on core/basic_models/requirement/basic_requirements.py
> +        from scenarios.scenario_models.field.field_filler_description import IntersectionFieldFiller
а чего импорт такой странный?

2021-02-24 13:25 UTC, nlpfsd commented on core/basic_models/requirement/basic_requirements.py
> +                    True: items.get('yes_words', []),
интерфейс странный, удобнее будет указывать только положительные случаи. К тому же сначала будут проверяться yes_words и получается что в no_words нет смысла.

2021-02-24 17:24 UTC, nlpfsd submitted a review, later dismissed

2021-02-25 09:30 UTC, christinadomanskaya approved these changes

2021-02-25 09:48 UTC, nlpfsd approved these changes

2021-02-25 11:55 UTC, merged