error message in incoming message
sberdevices/smart_app_framework pull request #61
Opened 2021-03-03 15:29 UTC by ElephantsFoot

error message in incoming message

2021-03-11 08:47 UTC, nlpfsd commented on smart_kit/start_points/main_loop_http.py
> +        except (json.JSONDecodeError, KeyError):
чутка промахнулся с try...except. Против пустого сообщения надо обернуть то что под ```if not message.validate():```

2021-03-11 09:32 UTC, ElephantsFoot commented on smart_kit/start_points/main_loop_http.py
> +        except (json.JSONDecodeError, KeyError):
там все поля lazy, поэтому value реально считается только здесь

2021-03-15 08:53 UTC, dangerink commented on smart_kit/start_points/main_loop_http.py
> +        except (json.JSONDecodeError, KeyError):
а точно все что здесь обернуто и может упасть относится к BAD_REQUEST? мб все-таки починить ответ если message.validate() не проходит? кажется логичнее же?
что там за беда с lazy?

2021-03-16 12:32 UTC, nlpfsd requested changes
надо перетащить try...except в другое место

2021-03-19 11:51 UTC, SokolovVladimir commented on smart_kit/start_points/main_loop_http.py
> +                        message=basic_error_message,
полагаю, это будет некорректно, возвращать в ответ такое сообщение
    {
         "messageName": "ERROR",
         "messageId": -1,
         "uuid": -1,
         "payload": {},
         "sessionId": -1
     }
     Ведь если происходит ошибка, необходимо по логике заполнить basic_error_message данными из входящего сообщения - mid, uuid, sessionId, в payload можно передать статус код, как мы описывали в доке на конфлю

2021-03-22 07:29 UTC, nlpfsd commented on smart_kit/start_points/main_loop_http.py
> +                        message=basic_error_message,
Этих данных нет. Здесь торчат фейковые айдишники чтобы ответ был в формате платформы.

2021-03-22 07:31 UTC, nlpfsd approved these changes

2021-03-22 10:53 UTC, christinadomanskaya approved these changes

2021-03-22 11:28 UTC, dangerink commented on core/message/from_message.py
> +        "uuid": -1,
"uuid" - словарь же по протоколу должен быть

2021-03-22 11:28 UTC, dangerink commented on core/message/from_message.py
> +        "uuid": -1,
"messageId":  - строка

2021-03-22 16:44 UTC, merged