Message validation
sberdevices/smart_app_framework pull request #64
Opened 2021-03-11 14:53 UTC by AivanF

So that apps can easily add custom validators or from plugins. But where to add the validation?

2021-03-15 07:04 UTC, ElephantsFoot requested changes

2021-03-15 07:04 UTC, ElephantsFoot commented on core/message/from_message.py
> +        print('validators:', validators)
принт

2021-03-15 07:04 UTC, ElephantsFoot commented on smart_kit/configs/__init__.py
> +    if not isinstance(app_config, Mock):
это плохая практика, ты подстраиваешь код под тесты. не понимаю зачем это, давай обсудим. уверен, есть другое решение

2021-03-15 21:53 UTC, AivanF commented on core/message/from_message.py
> +        print('validators:', validators)
Fixed

2021-03-15 21:53 UTC, AivanF commented on smart_kit/configs/__init__.py
> +    if not isinstance(app_config, Mock):
Fixed

2021-03-16 12:34 UTC, nlpfsd commented on core/message/from_message.py
>              log("Message headers is empty", level="ERROR")
давай вот это проверку на хидеры вытащим в дефолтный валидатор

2021-03-17 11:49 UTC, SokolovVladimir commented on core/message/from_message.py
>              log("Message headers is empty", level="ERROR")
Видимо должен появится отдельный валидатор для состава сообщения - header, payload и тд

2021-03-22 07:27 UTC, nlpfsd commented on smart_kit/start_points/main_loop_http.py
> +                                            validators=get_app_config().TO_MSG_VALIDATORS)
давай внутри класса вытягивает валидаторы из конфига если они не были переданы?

2021-03-22 10:20 UTC, AivanF commented on smart_kit/start_points/main_loop_http.py
> +                                            validators=get_app_config().TO_MSG_VALIDATORS)
Мы это на прошлой неделе обсуждали, что я изначально так и сделал, но у нас мессаджи в коре лежат, и туда не очень хорошо ложить циклическую/динамическую зависимость на get_app_config..

2021-03-22 10:24 UTC, AivanF commented on core/message/from_message.py
>              log("Message headers is empty", level="ERROR")
Решили, что валидируем payload, т.к остальная структура у нас инфраструктурная и статичная.

2021-03-24 11:34 UTC, ElephantsFoot approved these changes

2021-03-24 11:34 UTC, ElephantsFoot commented on tests/core_tests/mq_test/test_from_message.py
> +class PieMessageValidator(MessageValidator):
оно у тебя пироги валидирует?)
некритично, но pi

2021-03-25 08:04 UTC, AivanF commented on tests/core_tests/mq_test/test_from_message.py
> +class PieMessageValidator(MessageValidator):
Это типа маленький юмор, не портящий код :)

2021-03-26 15:15 UTC, christinadomanskaya approved these changes

2021-03-29 09:22 UTC, ElephantsFoot approved these changes

2021-03-29 09:25 UTC, ElephantsFoot approved these changes

2021-03-29 09:25 UTC, ElephantsFoot commented on smart_kit/start_points/app.py
> -    )
давно пора было это сделать, круто!

2021-03-31 07:38 UTC, AivanF commented on smart_kit/start_points/app.py
> -    )
😊👍

2021-04-01 14:18 UTC, ElephantsFoot approved these changes

2021-04-01 15:47 UTC, christinadomanskaya submitted a review, later dismissed

2021-04-01 18:55 UTC, ElephantsFoot approved these changes

2021-04-02 06:39 UTC, christinadomanskaya approved these changes

2021-04-02 07:33 UTC, merged