WIP parallel loop
sberdevices/smart_app_framework pull request #68
Opened 2021-03-22 15:46 UTC by nlpfsd

2021-03-23 07:59 UTC, dangerink commented
го писать нормальные коммит-сообщения ну

2021-03-23 08:31 UTC, SokolovVladimir commented on smart_kit/start_points/main_loop_kafka.py
> +            self.pre_handle()
Напрашивается post_handle для хелс чека

2021-03-23 09:05 UTC, SokolovVladimir submitted a review, later dismissed

2021-03-23 09:51 UTC, dangerink commented on smart_kit/start_points/main_loop_parallel_kafka.py
> +            time.sleep(self._step)
оно же будет тормозить майн поток, тогда уж это в отдельном потоке надо крутить, ктоме кафки в главном сейчас еще метрики и хелсчеки - они тормохзит начнут.

2021-03-23 09:51 UTC, dangerink commented on smart_kit/start_points/main_loop_parallel_kafka.py
> +            time.sleep(self._step)
мб просто убрать отсюда while ?

2021-03-23 09:51 UTC, dangerink commented on smart_kit/start_points/main_loop_kafka.py
> +        consumer.commit_offset(mq_message)
не запускал с пулом процессов? кажись не взлетит - нужно держать коннект в воркере, а объект consumer инициализован в главном процессе

2021-03-23 09:54 UTC, dangerink commented on smart_kit/start_points/main_loop_kafka.py
> +        self.iterate_behavior_timeouts()
если делать процессы - iterate_behavior_timeouts должен быть в каждом свой, иначе придется гонять словарики с сохраненными таймаутами, с потоками кажется тоже не оч правильно что таймауты обрабатываются в мейне, а не в воркерах

2021-03-29 07:44 UTC, AivanF commented on core/logging/logger_handlers.py
> +    def __init__(self, filename, mode='a', maxBytes=0, backupCount=0, encoding=None, delay=False):
Зачем camelCase?)

2021-03-29 14:21 UTC, dangerink approved these changes

2021-03-29 14:21 UTC, dangerink commented on smart_kit/start_points/main_loop_parallel_kafka.py
> +            super().process_message(mq_message, consumer, kafka_key, stats)
не достаточно ли в try-except заворачивать только super().process_message ?

2021-03-29 22:50 UTC, AivanF requested changes

2021-03-29 22:50 UTC, AivanF commented on smart_kit/start_points/main_loop_parallel_kafka.py
> +            if mutex and mutex.locked():
Может лучше `mutex.acquire() \n with mutex:  .process_message(..)` ? Будет лаконичнее и не надо в двух местах лок освобождать.

2021-03-29 22:50 UTC, AivanF commented on smart_kit/start_points/main_loop_parallel_kafka.py
> +            time.sleep(self._step)
Ок, я понял, что слип нужен для того, чтобы когда все воркеры заняты, главный поток не отнимал процессорное время опрашивая их... Но действительно, это слишком заблочит остальную логику до тех пор, пока хотя бы один воркер не освободится. А что, если в них всех попали сообщения от одного юзверя, и один поток завис с HTTP-запросом, а остальные повисли на мьютексе? Застопорится всё :( Поэтому солидарен с Андреем.

2021-03-29 22:50 UTC, AivanF commented on core/logging/logger_handlers.py
> +        pid = os.getpid()
Идентификатор берётся `os.getpid()`, хотя нигде используется только `ThreadPoolExecutor`, и соответственно всё запускается в разных потоках, но в одном процессе, и pid будет всегда одинаковый. Надо либо `ProcessPoolExecutors`/`os.fork()`/`multiprocessing` юзать для запуска кода и мульти-процессный лок как мьютекс, либо `threading.get_ident()` для идентификации потока.

2021-03-30 11:10 UTC, christinadomanskaya approved these changes

2021-03-30 11:11 UTC, AivanF approved these changes

2021-03-30 11:38 UTC, merged