WIP: Add functionality to perform classification, add ClassifierFiller & ClassifierRequirement
sberdevices/smart_app_framework pull request #69
Opened 2021-03-22 15:59 UTC by kseniavoronaya

2021-03-25 06:03 UTC, AivanF requested changes

2021-03-25 06:03 UTC, AivanF commented on core/basic_models/classifiers/basic_classifiers.py
> +class Classifier:
Может лучше назвать `ClassifierBase`?

2021-03-25 06:03 UTC, AivanF commented on core/basic_models/classifiers/basic_classifiers.py
> +class Classifier:
Может лучше назвать `ClassifierBase`?

2021-03-25 07:06 UTC, kseniavoronaya commented on core/basic_models/classifiers/basic_classifiers.py
> +        self._classifier_type = "meta"
@AivanF да, согласна что так выглядит лучше, исправила. Спасибо!

2021-03-25 07:09 UTC, kseniavoronaya commented on core/basic_models/classifiers/basic_classifiers.py
> +    """Класс не является самостоятельным типом классификатора. Расширяет функционал базового класса."""
@AivanF я думала об использование абстрактного класса в самом начале, но пришла к выводу что он здесь не особо нужен, как считаешь что нам это даст?)

2021-03-25 07:13 UTC, AivanF commented on core/basic_models/classifiers/basic_classifiers.py
> +    """Класс не является самостоятельным типом классификатора. Расширяет функционал базового класса."""
Более формально и точно прописать `Класс не является самостоятельным типом классификатора`, т.к сейчас из кода и названий Classifier и ExtendedClassifier это не следует :) Да и легко же это, один импорт, один декоратор.

2021-03-25 07:22 UTC, kseniavoronaya reviewed
сама начала ревью по ошибке

2021-03-25 07:22 UTC, kseniavoronaya commented on core/basic_models/classifiers/basic_classifiers.py
> +class Classifier:
@AivanF я руководствовалась следущей логикой: у нас в `basic_models` есть базовые классы для сущностей `class Action`, `class Counter`, `class Requirement`, `class Operator` и т.д., и все они без `Base` в название идут, поэтому я решила поддержать этот стиль и оставить просто `Classifier`. Ну и как бы все они в директории `basic_models` название которой предполагает что там содержатся базовые классы. Но готова обсудить этот момент еще :)

2021-03-25 08:00 UTC, AivanF commented on core/basic_models/classifiers/basic_classifiers.py
> +class Classifier:
Ок :)

2021-03-25 08:03 UTC, AivanF commented on core/basic_models/classifiers/basic_classifiers.py
> +        self.items = items if items else {}
Видно, что здесь настройки, но `items` звучит как набор однотипных элементов-данных.

2021-03-25 08:03 UTC, AivanF commented on core/basic_models/classifiers/basic_classifiers.py
> +        self.items = items if items else {}
Может переименовать в options/settings?

2021-03-25 15:18 UTC, kseniavoronaya commented on core/basic_models/classifiers/basic_classifiers.py
> +    """Класс не является самостоятельным типом классификатора. Расширяет функционал базового класса."""
@AivanF окей, согласна что из названий классов не очевидно что это не самостоятельные типы, поэтому унаследовала базовый класс от ABC и добавила @abstractmethod на нужные методы. Спасибо!

2021-03-25 15:20 UTC, AivanF commented on core/basic_models/classifiers/basic_classifiers.py
> +    """Класс не является самостоятельным типом классификатора. Расширяет функционал базового класса."""
😊👍

2021-03-26 06:56 UTC, kseniavoronaya commented on core/basic_models/classifiers/basic_classifiers.py
> +        self.items = items if items else {}
@AivanF окей, согласна, переименовала в `settings` :)

2021-03-29 13:48 UTC, dangerink commented on core/repositories/classifier_repository.py
> +            permitted_channels = classifier_params["channels"]
а этот замут с каналами из 1.0 нужен ли тут?

2021-03-29 13:48 UTC, dangerink commented on core/repositories/classifier_repository.py
> +        super(ClassifierRepository, self).fill(classifiers_dict)
мб гдето здесь и делать initial_launch? не нашел где он сейчас вызывается

2021-03-29 13:48 UTC, dangerink commented on core/utils/exception_handlers.py
> +                        on_error_obj_method_name else (lambda *x: on_error_return_res)
название не говорящее(не понятно из сигнатуры когда используется on_error_return_res а когда on_error_obj_method_name)

а нужно оно? 
не проще оставить только метод?

2021-04-01 11:29 UTC, kseniavoronaya commented on core/basic_models/classifiers/basic_classifiers.py
> +        return [self._answer_template(intent, 0, False) for intent in self.intents]
@dangerink нет, не влияет. "score = 0" установлен здесь тк мы не совершаем классификацию как таковую (модель не вызывается), поэтому "уверенность/вероятность" класса интента выставлена в ноль. Поставить в score 1 или любое другое рандомное значение из интервала [0,1] было бы не логичным. Ну и я опиралась на эту документацию: https://sbtatlas.sigma.sbrf.ru/wiki/display/NLP/Classifier дабы не сломать существующую ранее логику :)

2021-04-01 11:37 UTC, kseniavoronaya commented on core/basic_models/classifiers/basic_classifiers.py
> +        return {t[0]: t[1] for t in tuple_weights}
@dangerink хорошее замечание, исправила, спасибо

2021-04-01 13:21 UTC, kseniavoronaya commented on core/repositories/classifier_repository.py
> +            permitted_channels = classifier_params["channels"]
@dangerink обсудили в чате с командой, и пришли к выводу что сейчас проверка на каналы не нужна

2021-04-01 13:40 UTC, kseniavoronaya commented on core/utils/exception_handlers.py
> +                        on_error_obj_method_name else (lambda *x: on_error_return_res)
@dangerink функционал где только метод не дает гибкости, мне например, потребовалось возвращать пустой список а не None в случае эксепшена в методе классификатора:  
`
class ExternalClassifier

@exc_handler(handled_exceptions=(timeout_decorator.TimeoutError,), on_error_return_res=[])
 def find_best_answer(....)
`   
Можно попробовать назвать как то так: `return_res_if_not_obj_method`, достаточно длинное правда, но вроде суть отражает, как считаешь?

2021-04-01 22:59 UTC, kseniavoronaya commented on core/utils/exception_handlers.py
> +                        on_error_obj_method_name else (lambda *x: on_error_return_res)
@dangerink сделала через доп. метод, как обсудили:   
```
  @staticmethod
     def on_timeout_error(*args, **kwarg):
         return list()
```

2021-04-01 23:01 UTC, kseniavoronaya commented on core/repositories/classifier_repository.py
> +        super(ClassifierRepository, self).fill(classifiers_dict)
@dangerink согласна, хорошее замечание, добавила сюда функцию производящую начальный запуск классификаторов

2021-04-05 08:14 UTC, AivanF commented
Ещё насчёт файла `smart_kit/template/static/references/classifiers_data/ReadBookOrNotClassifier.pkl` – это же бинарный пикл? А он точно ли платформенно-независимый?

2021-04-05 08:14 UTC, AivanF commented on smart_kit/resources/__init__.py
> +        classifiers["external"] = ExternalClassifier
Здесь аналогично, может где-то сделать список классификаторов, и использовать здесь, не дублируя константы?

2021-04-05 14:09 UTC, kseniavoronaya commented
@AivanF что касается твоего вопроса насчет кросс-платформенности файла `ReadBookOrNotClassifier.pkl`: я использовала библиотеку `dill` (тот же самый pickle сериализатор только с расширенными возможностями), и да, объект (класс модели) сохранен в двоичном виде. Использовала стандартный/дефолтный дата формат, поэтому проблем с кросс-платформенностью быть не должно. И если ты посмотришь на наш класс `class DillRepository` то увидишь, что pickle файлы открываются на чтение там именно в бинарном режиме, что также не должно вызывать ошибок.

2021-04-05 14:16 UTC, kseniavoronaya commented on smart_kit/resources/__init__.py
> +        classifiers["external"] = ExternalClassifier
@AivanF в этом файле я старалась придерживаться общего стиля инициализации как и у остальных сущностей (смотри адаптеры, экшены, реквайременты и т.д любую другую), поэтому мне кажется лучше оставить так :)

2021-04-05 14:50 UTC, kseniavoronaya commented on core/basic_models/classifiers/classifiers_constants.py
> +SUPPORTED_CLASSIFIERS_TYPES = frozenset(["external", "scikit", "skip"])
@AivanF в принципе согласна, обновила это в последнем коммите :)

2021-04-07 08:12 UTC, AivanF approved these changes

2021-04-07 08:45 UTC, kseniavoronaya commented on core/basic_models/classifiers/basic_classifiers.py
> +            scenario_classifiers: Optional[Dict[str, Any]] = None
@christinadomanskaya, у нас просто в этом же файле на 17 строке уже создается переменная `classifiers`:  
```
classifiers = Registered()
classifier_factory = build_factory(classifiers)
```
поэтому этот аргумент назвала `scenario_classifiers` чтобы не было путаницы в именах

2021-04-07 08:48 UTC, kseniavoronaya commented on core/basic_models/classifiers/basic_classifiers.py
> +        self.version = settings.get("version", -1)
@christinadomanskaya окей, спасибо, уберу это тогда

2021-04-07 12:33 UTC, christinadomanskaya approved these changes

2021-04-07 14:50 UTC, merged